databases:
  - name: restaurant_db
    plan: free
    databaseName: restaurant_db_civd
    user: restaurant_db

services:
  - type: web
    plan: free
    name: restaurant_kitchen_service
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn restaurant_kitchen_service.wsgi:application --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
