# Generated by Django 5.0.3 on 2024-03-21 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_cook_years_of_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='time_for_using',
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='kitchen.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='best_before',
            field=models.DateField(null=True),
        ),
    ]
