# Generated by Django 5.0.3 on 2024-03-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_remove_ingredient_time_for_using_alter_dish_cooks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtype',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
