# Generated by Django 5.0.4 on 2024-12-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_dishtype_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                null=True, related_name="dishes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="dish_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kitchen.dishtype",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                null=True, related_name="dishes", to="kitchen.ingredient"
            ),
        ),
    ]
